BBlog.UI/Controllers/EmployeeTestController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace BBlog.UI.Controllers
{
    public class Class1
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public class EmployeeTestController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var httpClient = new HttpClient();
            var responseMessage = await httpClient.GetAsync("https://localhost:44305/api/Employee");
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<Class1>>(jsonString);
            return View(values);
        }
        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddEmployee(Class1 class1)
        {
            if (class1.Name != "" && class1.Name != null)
            {
                var httpClient = new HttpClient();
                var jsonEmployee = JsonConvert.SerializeObject(class1);
                StringContent content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
                var responseMessage = await httpClient.PostAsync("https://localhost:44305/api/Employee", content);
                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                return View(class1);
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> UpdateEmployee(int id)
        {
            var httpClient = new HttpClient();
            var responseMessage = await httpClient.GetAsync("https://localhost:44305/api/Employee/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonEmployee = await responseMessage.Content.ReadAsStringAsync();
                var value = JsonConvert.DeserializeObject<Class1>(jsonEmployee);
                return View(value);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateEmployee(Class1 class1)
        {
            if (class1.Name != "" && class1.Name != null)
            {
                var httpClient = new HttpClient();
                var jsonEmployee = JsonConvert.SerializeObject(class1);
                var content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
                var responseMessage = await httpClient.PutAsync("https://localhost:44305/api/Employee", content);
                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                return View(class1);
            }
            return View();
        }
        public async Task<IActionResult> DeleteEmployee(int id)
        {
            HttpClient httpClient = new HttpClient();
            var responseMessage = await httpClient.DeleteAsync("https://localhost:44305/api/Employee/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BBlog.UI/Views/EmployeeTest/AddEmployee.cshtml
@model BBlog.UI.Controllers.Class1
@{
    ViewData["Title"] = "Add Employee";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h3>
                        <i class="fa fa-plus"></i> Add Employee
                        <a href="/EmployeeTest/Index" style="position:absolute;right:40px"><i class="fa fa-arrow-left"></i></a>
                    </h3>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("AddEmployee", "EmployeeTest", FormMethod.Post))
                    {
                        <label><b>Name</b><b style="color:red">*</b></label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                        <br />
                        <button type="submit" class="btn btn-success">Add</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

BBlog.UI/Views/EmployeeTest/Index.cshtml
@model List<BBlog.UI.Controllers.Class1>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h3>
                        <i class="fa fa-list"></i> Employees
                        <a href="/EmployeeTest/AddEmployee" style="position:absolute;right:40px"><i class="fa fa-plus"></i></a>
                    </h3>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Delete</th>
                                <th>Name</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a href="/EmployeeTest/DeleteEmployee/@item.Id"><i style="color:red" class="fa fa-trash"></i></a>          
                                    </td>
                                    <td>@item.Name</td>
                                    <td>
                                        <a href="/EmployeeTest/UpdateEmployee/@item.Id"><i class="fa fa-edit fa-lg"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

BBlog.UI/Views/EmployeeTest/UpdateEmployee.cshtml
@model BBlog.UI.Controllers.Class1
@{
    ViewData["Title"] = "UpdateEmployee";
    Layout = "~/Areas/Admin/Views/_AdminLayout.cshtml";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h3>
                        <i class="fa fa-plus"></i> Update Employee
                        <a href="/EmployeeTest/Index" style="position:absolute;right:40px"><i class="fa fa-arrow-left"></i></a>
                    </h3>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("UpdateEmployee", "EmployeeTest", FormMethod.Post))
                    {
                        <label><b>Name</b><b style="color:red">*</b></label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                        <br />
                        <button type="submit" class="btn btn-success">Update</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>